# config/services.yaml
nats:
  host: nats.oca.lan
  port: 4222
  # required: true   # If true (default), block startup until NATS is available
                     # If false, use 2s timeout and continue without NATS if unavailable


services:
  - type: dumb_permanent
    log_level: INFO
    interval: 10
    instance_context: dev

  - type: dumb_complex
    log_level: INFO
    interval: 3
    instance_context: main

#  - type: plan_runner
#    log_level: INFO
#    instance_context: zb08
#
#  - type: guider
#    log_level: INFO
#    instance_context: zb08
#
#  - type: dome_follower
#    log_level: INFO
#    instance_context: zb08