nats:
  host: nats.oca.lan
  port: 4222

services:
  - type: hello_world
    instance_context: test
    interval: 3
    message: "Hello from new framework!"
    log_level: INFO
  
  - type: hello_world
    instance_context: fast
    interval: 1
    message: "Fast hello!"
    log_level: DEBUG